### ISSUE TITLE
Hello, why do UVI calculate in this way ?    

### ISSUE THREAD

**Issue by rak-ltp** [levkovigor/LTR390#1]
Hello, why do UVI calculate in this way ?     uviuvi = raw / ((gain_arr[_gain] / 18) * (res_factor[_resolution] / res_factor[0]) * 2300) * WFAC;

**Comment by rak-ltp** [comment]
![image](https://user-images.githubusercontent.com/89072247/131843812-612aa42e-63e8-41cf-8687-8ad7bf2d490b.png)

**Comment by levkovigor** [comment]
> 
> 
> Hello, why do UVI calculate in this way ? uviuvi = raw / ((gain_arr[_gain] / 18) * (res_factor[_resolution] / res_factor[0]) * 2300) * WFAC;

According to datasheet UV Sensitivity = 2300 at Gain range = 18, Resolution = 20-bit. So UVIcalc = RAW Data / 2300 * WFAC. But for other gain and resolution it should be recalculated

**Comment by rak-ltp** [comment]
I know your meaning,but the UV Sensitivity = 1400 at Gain range = 18, Resolution = 20-bit. 
![image](https://user-images.githubusercontent.com/89072247/131936493-a4c78776-1c3a-4e46-a441-03638e90ad1f.png)

**Comment by rak-ltp** [comment]
the datasheet version is 8-Dec-15,
![image](https://user-images.githubusercontent.com/89072247/131936577-75b96677-76a4-44a9-9e46-f94134e69a4a.png)

**Comment by levkovigor** [comment]
@rak-ltp Thank you for this information. I've contacted LITEON and they confirmed this information. The UV Index calculation has been corrected.

**Comment by rak-ltp** [comment]
ok,Thank you,May I ask which version of formula is used for calculation now

**Comment by rak-ltp** [comment]
I have seen your modification,Thank you
