### ISSUE TITLE
LTR390 Not Connected Error

### ISSUE THREAD

**Issue by jacobisbell** [levkovigor/LTR390#3]
Using adafruit's ltr390 sensor board connected via stemma qt, something in the initialization is failing. I don't yet have an environment setup to where I can debug the specific line that's causing the failure. I've attempted this with both an Uno R3 and Teensy 4.0 and both yield same result. The adafruit library example does work on the Uno R3 so I know it's physically connected correctly and I've confirmed the address is unchanged at 0x53. 

![image](https://user-images.githubusercontent.com/867730/132952172-ae13ed73-ca4b-4c90-bd22-ddeab7bf7d3c.png)

**Comment by levkovigor** [comment]
@jacobisbell I ll recheck it on Uno R3 next week. Last tests were made on ESP32.

**Comment by jacobisbell** [comment]
I've found the problem to be in the reset function. I don't know the 'why' behind the need for the ack but this is definitely what's causing the failure. 

![image](https://user-images.githubusercontent.com/867730/132953598-b9744dac-889e-43f1-9efe-512e31f68f15.png)

**Comment by levkovigor** [comment]
> I've found the problem to be in the reset function. I don't know the 'why' behind the need for the ack but this is definitely what's causing the failure.
> 
> ![image](https://user-images.githubusercontent.com/867730/132953598-b9744dac-889e-43f1-9efe-512e31f68f15.png)

Thank you, I understand the problem. Sometimes ltr390 can reset with i2c write register error but reset perform. So this string can be removed. 

Fixed in release 1.0.4

**Comment by jacobisbell** [comment]
Thank you. I found I did get values when I removed the string in my testing as well. After it began working I found the UVI was 0 but I'm assuming that'll be referencing issue #2

**Comment by levkovigor** [comment]
> Thank you. I found I did get values when I removed the string in my testing as well. After it began working I found the UVI was 0 but I'm assuming that'll be referencing issue #2

Try it with UV light source. Conventional bulbs are not a good source of UV radiation. Or check in good sunlight.

**Comment by levkovigor** [comment]
@jacobisbell 

New release - [1.0.6](https://github.com/levkovigor/LTR390/releases/tag/1.0.6)
    Error fixed in function getResoluton()
    Added data in csv files for Lux and UVI calculations at different gain and resolution values
    Added some data in csv files with comparisons of sensors: LTR390, VEML6070, VEML7700, SI1145
