### ISSUE TITLE
High UV Index value

### ISSUE THREAD

**Issue by metanav** [levkovigor/LTR390#4]
I am using an Adafruit LTR390 UV Light Sensor with Seeed Xiao (SAMD21). The latest example sketch (1.06) displays the results below. Why is it showing UV Index around 15 when the sensor is directly facing to sun at the noon 12:00 (temp 28 C)?

```
UV Index: 2.22
UVS: 3107
Ambient Light Lux: 18513.80
UV Index: 2.89
UVS: 4050
Ambient Light Lux: 19191.60
UV Index: 4.31
UVS: 6036
Ambient Light Lux: 50179.00
UV Index: 6.54
UVS: 9157
Ambient Light Lux: 42516.80
UV Index: 14.46
UVS: 20239
Ambient Light Lux: 52428.60
UV Index: 13.41
UVS: 18780
Ambient Light Lux: 52428.60
UV Index: 13.72
UVS: 19214
Ambient Light Lux: 52428.60
UV Index: 15.02
UVS: 21021
Ambient Light Lux: 52428.60
UV Index: 15.18
UVS: 21255
Ambient Light Lux: 52428.60
UV Index: 15.02
UVS: 21026

```

**Comment by levkovigor** [comment]
@metanav 
Hello, today I've tested LTR390 and VEML6070 with good UV source with beam power density near 400mW/m2 (405nm).
LTR390 gives UVI 15.09
VEML6070 - UVI 16.20

According to [research](https://files.eric.ed.gov/fulltext/EJ1105161.pdf) 
![image](https://user-images.githubusercontent.com/3767544/133394370-ff407a0b-d91e-4f6e-adc6-f6c60e446017.png)
for 400mW/m2  UVI = 400/25 = 16. So the data is correct for both sensors.

But it can be OK for UV source with narrow emission bandwidth. For sunlight with broad emission spectrum it can be incorrect and additional experiments should be carried out. To do this specialized equipment is needed. 

Also it should be studied the sunlight power density at direct beam.

**Comment by metanav** [comment]
Thanks @levkovigor for the explanation. So it means LTR390 or similar sensors are not suitable to calculate UVI for direct sun light. I am using LTR390 for an indoor setup. Can I rely on the UVI readings in the indoor environment during daytime with bright but indirect sunlight exposure?
