### ISSUE TITLE
Max lux

### ISSUE THREAD

**Issue by MarinusPretorius** [levkovigor/LTR390#6]
On a sunny day I get a max lux of 52428 from the getlux call. Any idea why.
I also get a very inconsistent uvi value. Even high as 8 on a normal day where the actual weather value is 3

**Comment by levkovigor** [comment]
@MarinusPretorius I think you got the measurement limit at this gain and resolution. Try lowering the gain and increasing the resolution. 

According to the UV, when measured in direct sunlight the UV index can be significantly higher than real.

**Comment by MarinusPretorius** [comment]
Awesome, thanks for getting back to me. I will play with gain an resolution tomorrow and let you know
